# client.toml
[client]
remote_addr = "ratregistry.gumshoe.au:2333" # The address of the server. The port must be the same with the port in `server.bind_addr`

[client.services.registry]
token = "use_a_secret_that_only_you_know"
local_addr = "127.0.0.1:5000"

[client.services.uireg]
token = "use_a_secret_that_only_you_know"
local_addr = "127.0.0.1:5001"

[client.services.ratwww]
token = "use_a_secret_that_only_you_know"
local_addr = "127.0.0.1:5003"

[client.services.ssh]
token = "use_a_secret_that_only_you_know"
local_addr = "127.0.0.1:22"               # SSH to local machine (accessed via ssh -p 2222 user@domain....
