# server.toml
[server]
bind_addr = "0.0.0.0:2333" # `2333` specifies the port that rathole listens for clients

[server.services.registry]
token = "use_a_secret_that_only_you_know"
bind_addr = "0.0.0.0:5000"

[server.services.uireg]
token = "use_a_secret_that_only_you_know"
bind_addr = "127.0.0.1:5001"

[server.services.ratgumshoe]
token = "use_a_secret_that_only_you_know"
bind_addr = "127.0.0.1:8083"

[server.services.rattaps]
token = "use_a_secret_that_only_you_know"
bind_addr = "127.0.0.1:8084"

[server.services.ssh]
token = "use_a_secret_that_only_you_know"
bind_addr = "0.0.0.0:2222"                # SSH access to client machine (use ssh -p 2222 user@domain...
